apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
        - name: react-ui
          image: react-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
